export interface CotizacionModel{
  tipoViaje?: string,
  regreso?: string,
  clientePagaCasetas?: string,
  idCotizacion?: number,
  folio?: string,
  idUnidadNegocio?: number,
  unidadNegocio?: string,
  idTipoOperacion?: number,
  tipoOperacion?: string,
  clasificacion?: string,
  cliente?: string,
  origen?: string,
  destino?: string,
  diesel?: number,
  costo?: number,
  FactorCargaSolcial?: number,
  distanciaTotal?: number,
  fletePorViaje?: number,
  numLlantas?: number,
  rendimientoKms?: number,
  rendimientoKmsVacio?:number,
  costoLlanta?: number,
  costoLlantaKmFull?: number,
  distanciaIda?: number,
  distanaciaRetorno?: number,
  casetas?: number,
  casetasRegreso?: number,
  dieselFinal?: number,
  tarifa?: number,
  costoPorKm?: number,
  ingresoPorKm?: number,
  tarifa25?: number,
  tarifa30?: number,
  tarifa35?: number,
  tarifa40?: number,
  porcentajeFinal?: number,
  tarifaFinal?: number,
  status?: string,
  precioVtaFinal?: number,
  dieselTotal?: number,
  variables?: VariablesCotizacionModel[],
  costos?: DetalleCotizacionModel[]
}
export interface VariablesCotizacionModel{
  variable: string,
  valor?: number
}

export interface DetalleCotizacionModel{
  descripcion: string,
  valor?: string,
  porcentaje?:number
}

export interface NuevaCotizacionModel{
  idCotizacion?:number,
  sencillo: boolean,
  regresa_vacio: boolean,
  id_ingreso: string,
  id_area: number,
  id_tipo_operacion: number,
  clasificacion: string,
  cliente: string,
  origen: string,
  destino: string,
  kms_ida: number,
  kms_regreso: number,
  casetas: number,
  casetas_regreso: number,
  diesel: number,
  num_llantas: number,
  rendimiento_cargado: number,
  rendimiento_vacio: number,
  costo_llanta: number,
  costo_llanta_km_full: number,
  tarifaFinal?: number,
  dieselTotal
}
